build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
          compile_options: '--enable-gd'
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - 'tests/*'

tools:
  external_code_coverage: true

checks:
  php: true
